edition = "2021"
blank_lines_upper_bound = 2
condense_wildcard_suffixes = true
group_imports = "StdExternalCrate"
fn_args_layout = "Tall"
imports_granularity = "Preserve"
use_small_heuristics = "Max"
fn_single_line = true
match_block_trailing_comma = true
normalize_comments = true
enum_discrim_align_threshold = 20
use_field_init_shorthand = true
use_try_shorthand = true
max_width = 90
struct_lit_single_line = true
reorder_impl_items = true
chain_width = 90
